#!/bin/dash
set -x

echo -n "Wait for lets encrypt certificate to be installed"

SNAPCTL=snapctl

while [ "`${SNAPCTL}` get fqdn" == "" ]; do
	sleep 15m
done

echo "FQDN has been configured by getcert."
echo "Running certificate renewal every 15min"

FQDN="`${SNAPCTL}` get fqdn"

while true; do

	# run cert bot renewal
 	certbot certonly \
	 --standalone \
	 --noninteractive \
	 --domain ${FQDN} \
	 --agree-tos \
	 --email ${EMAIL} \
	 --config-dir ${SNAP_USER_DATA}/letsencrypt/config \
	 --work-dir ${SNAP_USER_DATA}/letsencrypt/work \	
	 --logs-dir ${SNAP_USER_DATA}/letsencrypt/logs \
	 --cert-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --key-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --fullchain-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --deploy-hook ${SNAP}/letsencrypt/renewal-hooks/deploy 
	 #--test-cert \
	 #--staging
	 #--dry-run \
	sleep 15m
done
