#!/bin/bash
#set -x

echo 
echo "tomcat-with-ssl cron running certificate renewal" &>> ${LOG_FILE}
echo 

# setup for loggin
mkdir -p ${SNAP_USER_DATA}/cron
LOG_FILE=${SNAP_USER_DATA}/cron/renew.log
SNAPGET="snapctl get"

# wait until 'getcert' has obtained the initial certificate
echo -n "Wait for initial lets encrypt certificate to be installed"
FQDN=`${SNAPGET} fqdn` 
echo ${FQDN}
while [ "${FQDN}" == "" ]; do
	sleep 15m
	FQDN=`${SNAPGET} fqdn`
done


# the initial certificate now exists so ever 15 mins lets check if we need to renew

EMAIL=`${SNAPGET} email` 
CERTIFICATE_TYPE=`${SNAPGET} certificatetype` 
echo email=$EMAIL &>> ${LOG_FILE}
echo certificatetype=$CERTIFICATE_TYPE &>> ${LOG_FILE}
echo fqdn=$FQDN &>> ${LOG_FILE}

echo "FQDN has been configured by getcert."
echo "Running certificate renewal every 15min"
while true; do

	# run cert bot renewal
 	certbot certonly ${CERTIFICATE_TYPE} \
	 --webroot -w ${SNAP_DATA}/webapps \
	 --noninteractive \
	 --domain ${FQDN} \
	 --agree-tos \
	 --email ${EMAIL} \
	 --config-dir ${SNAP_USER_DATA}/letsencrypt/config \
	 --work-dir ${SNAP_USER_DATA}/letsencrypt/work \
	 --logs-dir ${SNAP_USER_DATA}/letsencrypt/logs \
	 --cert-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --key-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --fullchain-path ${SNAP_USER_DATA}/letsencrypt/config/live/${FQDN} \
	 --deploy-hook ${SNAP}/letsencrypt/renewal-hooks/deploy  &>>${LOG_FILE}

	sleep 15m
done
