#!/bin/dash
set -x

#temp hacks
SNAPNAME=tomcat-with-ssl
#end hacks	

# If no arguments, print usage statement & exit from function
if [ "$#" -ne "2" ]; then
	echo
	echo "Usage: getcert <emailaddress> <fqdn> "
	echo
	echo "Runs runs certbot to obtain an SSL certificate for <fqdn>."
	echo  The email address is used by letsencrypt to notify you of certificate issues.
	echo
	echo "<emailaddress> the email address for letsencrypt to send notifications to"
	echo "<fqdn> the fqdn to request a certificate for."
	exit 1 
fi


EMAIL=$1
FQDN=$2

# generate random password for keystore
KEYSTOREPWD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

#mkdir -p /etc/letsencrypt/live/${FQDN}

# check if the certificate already exists and if so lets delete it.
# if we don't delete the cert dir certbot will use a different name so our later steps won't find the certs.
if [ -e "/etc/letsencrypt/live/${FQDN}" ]; then
	echo rm -rf "/etc/letsencrypt/live/${FQDN}"
	#rm -rf "/etc/letsencrypt/live/${FQDN}"
	#certbot delete --cert-name home.noojee.org
fi


# run cert bot to obtain certificates
 certbot certonly \
	 --standalone \
	 --noninteractive \
	 --domain ${FQDN} \
	 --agree-tos \
	 --email ${EMAIL} \
	 --cert-path /etc/letsencrypt/live/${fQDN} \
	 --key-path  /etc/letsencrypt/live/${fQDN} \
	 --fullchain-path  /etc/letsencrypt/live/${fQDN} \
	 --test-cert \
	 --staging
	 #--dry-run \


mkdir -p ${SNAP_DATA}/etc/tomcat8/keystore

# create pkcs12 store
openssl pkcs12 -export \
  -in /etc/letsencrypt/live/${FQDN}/fullchain.pem \
  -inkey /etc/letsencrypt/live/${FQDN}/privkey.pem \
  -out ${SNAP_DATA}/etc/tomcat8/keystore/${FQDN}.p12 \
 -password pass:${KEYSTOREPWD}

# import pkcs12 store int java keystore.
keytool -importkeystore \
 -noprompt \
 -srckeystore ${SNAP_DATA}/etc/tomcat8/keystore/${FQDN}.p12 \
 -srcstoretype pkcs12 \
 -srcstorepass ${KEYSTOREPWD} \
 -destkeystore ${SNAP_DATA}/etc/tomcat8/keystore/${FQDN}.keystore \
 -deststoretype jks \
 -deststorepass ${FQDN}

SERVERXML="${SNAP_DATA}/conf/server.xml"
SERVERXML_BACKUP="${SNAP_DATA}/conf/server.xml.backup"
if [ -e "${SERVERXML_ORG}" ]; then
	echo "server.xml already backedup"
else
	 mkdir -p ${SNAP_DATA}/conf
	 cp ${SERVERXML} ${SERVERXML_BACKUP}
fi

# overwrite the default tomcat config file with our SSL enabled one along with the keystore password
sed  -e 's/%FQDN%/'${FQDN}'/g' \
	-e 's/%KEYSTOREPWD%/'${KEYSTOREPWD}'/g' \
	< ${SNAP}/tomcat-server-with-ssl.xml \
	> "${SERVERXML}"

snap restart ${SNAP_NAME}
