#!/bin/dash

set -x

SNAPCTL=snapctl

#temp hacks
SNAPNAME=pi-gation
SNAPCTL=snap
#end hacks	

# after a cert renewal we need to install the certs into the java keystore

KEYSTOREPWD="`${SNAPCTL}` get keystorepwd"
FQDN="`${SNAPCTL}` get fqdn"

# re-create pkcs12 store
openssl pkcs12 -export \
  -in ${SNAP_DATA}/letsencrypt/live/${FQDN}/fullchain.pem \
  -inkey ${SNAP_DATA}/letsencrypt/live/${FQDN}/privkey.pem \
  -out ${SNAP_DATA}/keystore/${FQDN}.p12 \
 -password pass:${KEYSTOREPWD}

# import pkcs12 store int java keystore.
keytool -importkeystore \
 -noprompt \
 -srckeystore ${SNAP_DATA}/tomcat8/keystore/${FQDN}.p12 \
 -srcstoretype pkcs12 \
 -srcstorepass ${KEYSTOREPWD} \
 -destkeystore ${SNAP_DATA}/tomcat8/keystore/${FQDN}.keystore \
 -deststoretype jks \
 -deststorepass ${FQDN}

${SNAPCTL} restart
