---
name: tomcat-with-ssl
version: '0.1'  # just for humans, typically '1.2+git' or '1.3.2'
summary: Apache Tomcat with SSL activated and managed by Certbot.
description: |
  Intended to use as a part to install Apache Tomcat with
  SSL enabled and the required certificate automatically
  managed by certbot (Lets Encrypt) including automatica renewals.
  Note: current if a renewal occurs tomcat will be restarted without warning.

hooks:
  configure:
    plugs: [home]

parts:

  tomcat-with-ssl:
    plugin: ant
	soruce: https://svn.apache.org/repos/asf/tomcat/tc8.5.x/trunk/
    source-type: git
    after: [setup-repo, getcert]
    prime:
      - -webapps/docs
      - -webapps/examples
      - -webapps/manager
      - -webapps/host-manager
      - -webapps/ROOT
    override-build: |
      echo "Pre build steps"
      cp build.properties.default build.properties
      snapcraftctl build
      echo "Post build steps"
      cp -r output/build/* $SNAPCRAFT_PART_INSTALL
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/tomcat-launch
      #!/bin/sh
      export JRE_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export JAVA_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export CATALINA_HOME=\${SNAP}
      export CATALINA_BASE=\${SNAP_DATA}
      export CATALINA_TMPDIR=/tmp
      cp -rn \${CATALINA_HOME}/conf \${CATALINA_BASE}/
      # this creates a second copy of the webapps directory.
      # No problem but need to see if we can clean up.
      # seems like an organize statement might do the trick.
      cp -rn \${CATALINA_HOME}/webapps \${CATALINA_BASE}/
      exec \${CATALINA_HOME}/bin/catalina.sh run
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/tomcat-launch
    stage-packages:
      - libc6
      - libbz2-1.0
      - libgcc1
      - libcomerr2
      - libgcrypt20
      - liblzma5
      - libmount1
      - libncursesw5
      - libselinux1
      - libtinfo5
      - libuuid1
      - libstdc++6
      - libsmartcols1
      - libgpg-error0
      - libblkid1
      - zlib1g
      - libpcre3
      - libsystemd0
