name: tomcat-with-ssl
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Apache Tomcat with SSL activated and managed by Certbot.
description: | 
  Intended to use as a part to install Apache Tomcat with
  SSL enabled and the required certificate automatically 
  managed by certbot (Lets Encrypt) including automatica renewals.
  Note: current if a renewal occurs tomcat will be restarted without warning.
  
hooks:
  configure:
    plugs: [home]

parts: 

# certbot not available in standard repos so we need to add a repository
  setup-repo:
    plugin: nil
    prepare: |
      apt-get update --yes
      apt-get install --yes software-properties-common
      add-apt-repository --yes ppa:certbot/certbot
      apt-get update --yes
      apt-get install --yes certbot
 
  getcert:
    plugin: dump
    source: snap/getcert
    ## run our renew script as a certbot post renewal deploy script
    ## this installs the certs into the java keystore and restarts tomcat.
    #organize: 
      #renewal : letsencrypt/renewal-hooks/deploy
    after: [setup-repo]
    stage-packages:
      - certbot
      - libc6
      - libdb5.3

  tomcat-with-ssl:
    plugin: ant
    source: https://github.com/apache/tomcat85.git
    source-type: git
    prepare: |
      cp build.properties.default build.properties
    #organize:
      #snap/src/scripts/tomcat-launch : tomcat-launch
	after: [getcert]
    prime:
      - -webapps/docs
      - -webapps/examples
      - -webapps/manager
      - -webapps/host-manager
      - -webapps/ROOT
    install: |
      cp -r output/build/* $SNAPCRAFT_PART_INSTALL
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/tomcat-launch
      #!/bin/sh
      export JRE_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export JAVA_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export CATALINA_HOME=\${SNAP}
      export CATALINA_BASE=\${SNAP_DATA}
      export CATALINA_TMPDIR=/tmp
      cp -rn \${CATALINA_HOME}/conf \${CATALINA_BASE}/
      cp -rn \${CATALINA_HOME}/webapps \${CATALINA_BASE}/
      exec \${CATALINA_HOME}/bin/catalina.sh run
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/tomcat-launch
    stage-packages:
      - libc6
      - libbz2-1.0
      - libgcc1
      - libcomerr2
      - libgcrypt20
      - liblzma5
      - libmount1
      - libncursesw5
      - libselinux1
      - libtinfo5
      - libuuid1
      - libstdc++6
      - libsmartcols1
      - libgpg-error0
      - libblkid1
      - zlib1g
      - libpcre3
      - libsystemd0



