#!/bin/sh
ARCH=`uname -m`
if [ "$SNAP_ARCH" != "arm64" ] && [ "$SNAP_ARCH" != "armhf" ]; then
	# Run the simulator as we are not on RPi hardware
	export PI4J_PLATFORM="Simulated"
	export SimulatedPlatform="RaspberryPi GPIO Provider"
fi
export pi_gation_db_username="`snap get pi-gation db-username`"
export pi_gation_db_password="`snap get pi-gation db-password`"
export pi_gation_https_port="`snap get pi-gation https-port`"
${SNAP}/tomcat-launch

